### ISSUE TITLE
Kotlin Serialization Plugin Version Conflict with Kotlin 2.0.20

### ISSUE THREAD

**Issue by leehyeonbin** [781flyingdutchman/background_downloader#521]
**Describe the bug**
The background_downloader package has a hardcoded Kotlin serialization plugin version (1.9.22) in its Android build.gradle file, which causes version conflicts when the host project uses Kotlin 2.0.20. This results in a build failure due to plugin compatibility issues.

**To Reproduce**
1. Create a Flutter project with Kotlin 2.0.20
2. Add background_downloader: ^9.2.3 to pubspec.yaml
3. Run flutter pub get
4. Try to build the project with flutter run
5. See the Kotlin serialization plugin version conflict error
**Expected behavior**
The background_downloader package should either:
* Support Kotlin 2.0.20 by updating the serialization plugin version
* Remove the hardcoded version to allow the host project's version to be used
* Provide clear documentation about Kotlin version compatibility

**Logs**
If possible, include logs that capture the issue:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ihyeonbin/.pub-cache/hosted/pub.dev/background_downloader-9.2.3/android/build.gradle' line: 4

* What went wrong:
Error resolving plugin [id: 'org.jetbrains.kotlin.plugin.serialization', version: '1.9.22', apply: false]
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.

* Try:
* Run with --stacktrace option to get the stack trace.
* Run with --info or --debug option to get more log output.
* Run with --scan to get full insights.
* Get more help at https://help.gradle.org.

BUILD FAILED in 6s
Error: Gradle task assembleQaDebug failed with exit code 1
```

<img width="849" height="381" alt="Image" src="https://github.com/user-attachments/assets/58c8ba17-61c9-4768-bf2b-de46ff48e262" />

**Code**

// Current problematic code in background_downloader-9.2.3/android/build.gradle
id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.22' apply false```

Host project configuration (android/build.gradle):
```
buildscript {
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-serialization:2.0.20'
    }
}
```

Host project configuration (android/settings.gradle):
```
plugins {
    id "org.jetbrains.kotlin.android" version "2.0.20" apply false
    id "org.jetbrains.kotlin.plugin.compose" version "2.0.20" apply false
}
```

Host project configuration (android/app/build.gradle):
```
plugins {
    id "kotlinx-serialization"
    id "org.jetbrains.kotlin.plugin.compose"
}
```

**Additional context**
* This issue affects projects using Kotlin 2.0.20 or higher
* The workaround is to manually remove the version specification from the library's build.gradle file after each flutter pub get
* This creates collaboration issues as every team member needs to perform this manual fix
* The serialization plugin functionality works fine with Kotlin 2.0.20, so removing the hardcoded version should not break functionality
* Consider removing the version specification to allow the host project's Kotlin version to be used, or update to support Kotlin 2.0.20

**Comment by thefdisk** [comment]
Hai @leehyeonbin , How did you solve the problem?

**Comment by mentz-nmi** [comment]
> Your error message says: The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
> 
> That is the issue. The inclusion of version 1.9.20 in the package is simply a minimum - a properly configured application that uses Kotlin 2.1 or so will override this and force the use of that version. If that's not happening then that's because either you didn't configure your app build.gradle or another dependency is forcing something incompatible.

this might not be true @781flyingdutchman . we are using kotlin 2.0.0 and I still get the error:

```
* What went wrong:
Execution failed for task ':efa_push_plugin:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
First I had to specify the 'org.jetbrains.kotlin.plugin.serialization' in my setting.gradle, to have a new error 😄 
 I tried with version 2.0.0 but I got error so I used a closer version 1.9.24: `id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.24' apply false`
but it still gave me the error :
```
* What went wrong:
Error resolving plugin [id: 'org.jetbrains.kotlin.plugin.serialization', version: '1.9.22']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with a different version (1.9.24).
```

I had to use  `id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.22' apply false` in my package to pass this error. but I cannot use this version or any version lower that 2.0.0 because of some conflicts with other packages.


I'm not very familiar with how to set a minimum for a package so I'm not making a PR but I used this code in your package locally instead of setting it in the plugin{} and it worked:

``` kotlin
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

group 'com.bbflight.background_downloader'
version '1.0-SNAPSHOT'

def requiredMinimumVersion = '1.9.22'
def detectedKotlinVersion = null

// The standard for Flutter projects is to define the Kotlin version in the
// root project's 'ext' properties. This is the most reliable place to look.
// We access the main app's project using `rootProject`.
if (rootProject.hasProperty('ext') && rootProject.ext.has('kotlin_version')) {
    // If the property exists, get the version string.
    detectedKotlinVersion = rootProject.ext.get('kotlin_version')
}

// If the plugin dependency was found, proceed with the version check.
if (detectedKotlinVersion != null) {
    println("detectedKotlinVersion: ${detectedKotlinVersion}")

    // A simple text comparison is often sufficient for this check.
    // For more complex rules, a proper version comparison library would be used.
    if (detectedKotlinVersion < requiredMinimumVersion) {
        // If the detected version is lower than our minimum requirement,
        // we stop the build immediately and throw a custom GradleException.
        throw new GradleException(
            "\n\n[my_data_serializer] ERROR: Incompatible Kotlin Version.\n" +
            "This package requires at least Kotlin version ${requiredMinimumVersion} for its serialization features.\n" +
            "Your project is currently using version ${detectedKotlinVersion}.\n\n" +
            "SOLUTION: Please update the Kotlin version in your main project's `android/build.gradle`\n" +
            "or, preferably, in the `pluginManagement` block of your `android/settings.gradle` file.\n"
        )
    }
} else {
    // If we can't find the version for some reason, print a warning but allow the build to continue.
    
    println("Warning: [your_package_name] Could not determine the app's Kotlin version. Please ensure you are using at least Kotlin ${requiredMinimumVersion} to avoid build errors.")
}

```
